AdvertisementApp.UI/Controllers/AdvertisementController.cs
using AdvertisementApp.Business.Interfaces;
using AdvertisementApp.Common.Enums;
using AdvertisementApp.Dtos;
using AdvertisementApp.UI.Extensions;
using AdvertisementApp.UI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AdvertisementApp.UI.Controllers
{
    public class AdvertisementController : Controller
    {
        private readonly IAppUserService _appUserService;
        private readonly IAdvertisementAppUserService _advertisementAppUserService;

        public AdvertisementController(IAppUserService appUserService, IAdvertisementAppUserService advertisementAppUserService)
        {
            _appUserService = appUserService;
            _advertisementAppUserService = advertisementAppUserService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Roles = "Member")]
        public async Task<IActionResult> Apply(int advertisementId)
        {
            var userId = int.Parse((User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier)).Value);
            var userResponse = await _appUserService.GetByIdAsync<AppUserListDto>(userId);
            ViewBag.GenderId = userResponse.Data.GenderId;

            var items = Enum.GetValues(typeof(MilitaryStatusType));

            var list = new List<MilitaryStatusListDto>();
            foreach (int item in items)    //item => 1,2,3 etc.
            {
                list.Add(new MilitaryStatusListDto
                {
                    Id = item,
                    Definition = Enum.GetName(typeof(MilitaryStatusType), item)   //done,delayed,exempt etc.
                });
            }
            ViewBag.MilitaryStatus = new SelectList(list, "Id", "Definition");
            return View(new AdvertisementAppUserCreateModel
            {
                AdvertisementId = advertisementId,
                AppUserId = userId,


            });
        }

        [Authorize(Roles = "Member")]
        [HttpPost]
        public async Task<IActionResult> Apply(AdvertisementAppUserCreateModel model)
        {
            AdvertisementAppUserCreateDto dto = new();

            if (model.CvFile != null)
            {
                var fileName = Guid.NewGuid().ToString();
                var extName = Path.GetExtension(model.CvFile.FileName);
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "cvfiles", fileName + extName);
                var stream = new FileStream(path, FileMode.Create);
                await model.CvFile.CopyToAsync(stream);
                dto.CvPath = path;
            }

            dto.AdvertisementAppUserStatusId = model.AdvertisementAppUserStatusId;
            dto.AdvertisementId = model.AdvertisementId;
            dto.AppUserId = model.AppUserId;
            dto.EndDate = model.EndDate;
            dto.MilitaryStatusId = model.MilitaryStatusId;
            dto.WorkExperience = model.WorkExperience;

            var response = await _advertisementAppUserService.CreateAsync(dto);
            if (response.ResponseType == ResponseType.ValidationError)
            {
                foreach (var error in response.ValidationErrors)
                {
                    ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                }
                var userId = int.Parse((User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier)).Value);
                var userResponse = await _appUserService.GetByIdAsync<AppUserListDto>(userId);
                ViewBag.GenderId = userResponse.Data.GenderId;

                var items = Enum.GetValues(typeof(MilitaryStatusType));

                var list = new List<MilitaryStatusListDto>();
                foreach (int item in items)    //item => 1,2,3 etc.
                {
                    list.Add(new MilitaryStatusListDto
                    {
                        Id = item,
                        Definition = Enum.GetName(typeof(MilitaryStatusType), item)   //done,delayed,exempt etc.
                    });
                }
                ViewBag.MilitaryStatus = new SelectList(list, "Id", "Definition");
                return View(model);

            }
            else
            {
                return RedirectToAction("HumanResource", "Home");
            }

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> List()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Applied);
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> SetStatus(int advertisementAppUserId, AdvertisementAppUserStatusType type)
        {
            await _advertisementAppUserService.SetStatusAsync(advertisementAppUserId, type);
            return RedirectToAction("List");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ApprovedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.Interviewed);
            return View(list);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> RejectedList()
        {
            var list = await _advertisementAppUserService.GetList(AdvertisementAppUserStatusType.NegativeResult);
            return View(list);
        }

    }
}

AdvertisementApp.UI/Views/Advertisement/Apply.cshtml
@model AdvertisementAppUserCreateModel

<form class="w-75 mx-auto p-3" asp-action="Apply" asp-controller="Advertisement" method="post" enctype="multipart/form-data">
	<input type="hidden" asp-for="@Model.AdvertisementId" />
	<input type="hidden" asp-for="@Model.AppUserId" />
	@if (ViewBag.GenderId == (int)GenderType.Male)
	{
		<div class="mb-3">
			<label>Military Status:</label>
			<select onchange="setInputVisibility()" asp-for="@Model.MilitaryStatusId" asp-items="@ViewBag.MilitaryStatus" class="form-select">
			</select>
		</div>
		<div id="dateDiv" class="mb-3" style="display:none">
			<label>Until When?</label>
			<input type="date" asp-for="@Model.EndDate" class="form-control" />
		</div>
	}
	else
	{
		<input type="hidden" asp-for="@Model.MilitaryStatusId" value="@((int)MilitaryStatusType.Exempt)" />
	}

	<div class="mb-3">
		<label>Work Experience(annualy):</label>
		<input type="number" asp-for="@Model.WorkExperience" class="form-control" />
	</div>

	<div class="mb-3">
		<label>Upload Your Cv:</label>
		<input type="file" asp-for="@Model.CvFile" class="form-control" />
	</div>

	<div class="mb-3">
		<button type="submit" class="btn btn-primary">Save</button>
	</div>

	<div asp-validation-summary="All" class="text-danger"> </div>

</form>

@section script{
<script>
	setInputVisibility();
	function setInputVisibility(){
		
		var selectElement =document.getElementById("MilitaryStatusId");
		var militaryStatusId= selectElement.value;
		var dateDivElement= document.getElementById("dateDiv");
		if(militaryStatusId==2)
		{
			dateDivElement.style.display="block";
		}
		else{
			dateDivElement.style.display="none";
		}
	}
</script>
}

AdvertisementApp.UI/Views/Advertisement/ApprovedList.cshtml
@model List<AdvertisementAppUserListDto>
<div class="container-fluid">
@{
	if (Model?.Count > 0)
	{
		<div class="text-end my-3 p-1"> 
		   <a asp-action="List" asp-controller="Advertisement">New Applicants</a> |
		   <a asp-action="RejectedList" asp-controller="Advertisement">Rejected Applicants</a>
		</div>
		<table class="mt-3 table table-sm table-hover table-striped">
			<thead>
				<tr>
					<th>Applied Advertisement</th>
					<th>Applying Person</th>
					<th>Gender</th>
					<th>Job Advertisement Status</th>
					<th>Military Status</th>
					<th>Delay Until When</th>
					<th>Work Experience</th>
					<th>Process</th>


				</tr>
			</thead>
			<tbody>
				@foreach (var advertisementAppUser in Model)
				{
					<tr>
						<td>@advertisementAppUser.Advertisement.Title</td>
						<td>@advertisementAppUser.AppUser.Firstname @advertisementAppUser.AppUser.Surname</td>
						<td>@advertisementAppUser.AppUser.Gender.Definition</td>
						<td>@advertisementAppUser.AdvertisementAppUserStatus.Definition</td>
						<td>@advertisementAppUser.MilitaryStatus.Definition</td>
						<td>@(advertisementAppUser.EndDate==null?"Exempt or Done":@advertisementAppUser.EndDate?.ToString("MM/dd/yyyy"))</td>
						<td>@advertisementAppUser.WorkExperience</td>
						<td>
						
						<a asp-route-advertisementAppUserId="@advertisementAppUser.Id"  asp-route-type="@((int)AdvertisementAppUserStatusType.NegativeResult)"  asp-action="SetStatus" asp-controller="Advertisement" >Reject</a>
						</td>
					</tr>
				}

			</tbody>

		</table>
	}
	else
	{
		<div class="text-end my-3 p-1"> 
		   <a asp-action="List" asp-controller="Advertisement">New Applicants</a> |
		   <a asp-action="RejectedList" asp-controller="Advertisement">Rejected Applicants</a>
		</div>
		<div class="mt-3 text-center lead">It cannot be found any advertisements</div>
	}

}
</div>

AdvertisementApp.UI/Views/Advertisement/List.cshtml
@model List<AdvertisementAppUserListDto>
<div class="container-fluid">
@{
	if (Model?.Count > 0)
	{
		<div class="text-end my-3 p-1"> 
		   <a asp-action="ApprovedList" asp-controller="Advertisement">Applicants for interview</a> |
		   <a asp-action="RejectedList" asp-controller="Advertisement">Rejected Applicants</a>
		</div>
		<table class="mt-3 table table-sm table-hover table-striped">
			<thead>
				<tr>
					<th>Applied Advertisement</th>
					<th>Applying Person</th>
					<th>Gender</th>
					<th>Job Advertisement Status</th>
					<th>Military Status</th>
					<th>Delay Until When</th>
					<th>Work Experience</th>
					<th>Process</th>


				</tr>
			</thead>
			<tbody>
				@foreach (var advertisementAppUser in Model)
				{
					<tr>
						<td>@advertisementAppUser.Advertisement.Title</td>
						<td>@advertisementAppUser.AppUser.Firstname @advertisementAppUser.AppUser.Surname</td>
						<td>@advertisementAppUser.AppUser.Gender.Definition </td>
						<td>@advertisementAppUser.AdvertisementAppUserStatus.Definition</td>
						<td>@advertisementAppUser.MilitaryStatus.Definition</td>
						<td>@(advertisementAppUser.EndDate==null?"Exempt or Done":@advertisementAppUser.EndDate?.ToString("MM/dd/yyyy"))</td>
						<td>@advertisementAppUser.WorkExperience</td>
						<td>
						<a asp-route-advertisementAppUserId="@advertisementAppUser.Id" asp-route-type="@((int)AdvertisementAppUserStatusType.Interviewed)" asp-action="SetStatus" asp-controller="Advertisement" >Call for interview</a>
						<a asp-route-advertisementAppUserId="@advertisementAppUser.Id"  asp-route-type="@((int)AdvertisementAppUserStatusType.NegativeResult)"  asp-action="SetStatus" asp-controller="Advertisement" >Reject</a>
						</td>
					</tr>
				}

			</tbody>

		</table>
	}
	else
	{
		<div class="text-end my-3 p-1"> 
		   <a asp-action="ApprovedList" asp-controller="Advertisement">Applicants for interview</a> |
		   <a asp-action="RejectedList" asp-controller="Advertisement">Rejected Applicants</a>
		</div>
		<div class="mt-3 text-center lead">It cannot be found any advertisements</div>
	}

}
</div>

AdvertisementApp.UI/Views/Advertisement/RejectedList.cshtml
@model List<AdvertisementAppUserListDto>
<div class="container-fluid">
@{
	if (Model?.Count > 0)
	{
		<div class="text-end my-3 p-1"> 
		   <a asp-action="ApprovedList" asp-controller="Advertisement">Applicants for interview</a> |
		   <a asp-action="List" asp-controller="Advertisement">New Applicants</a>
		</div>
		<table class="mt-3 table table-sm table-hover table-striped">
			<thead>
				<tr>
					<th>Applied Advertisement</th>
					<th>Applying Person</th>
					<th>Gender</th>
					<th>Job Advertisement Status</th>
					<th>Military Status</th>
					<th>Delay Until When</th>
					<th>Work Experience</th>
					<th>Process</th>


				</tr>
			</thead>
			<tbody>
				@foreach (var advertisementAppUser in Model)
				{
					<tr>
						<td>@advertisementAppUser.Advertisement.Title</td>
						<td>@advertisementAppUser.AppUser.Firstname @advertisementAppUser.AppUser.Surname</td>
						<td>@advertisementAppUser.AppUser.Gender.Definition</td>
						<td>@advertisementAppUser.AdvertisementAppUserStatus.Definition</td>
						<td>@advertisementAppUser.MilitaryStatus.Definition</td>
						<td>@(advertisementAppUser.EndDate==null?"Exempt or Done":@advertisementAppUser.EndDate?.ToString("MM/dd/yyyy"))</td>
						<td>@advertisementAppUser.WorkExperience</td>
						<td>
						<a asp-route-advertisementAppUserId="@advertisementAppUser.Id" asp-route-type="@((int)AdvertisementAppUserStatusType.Interviewed)" asp-action="SetStatus" asp-controller="Advertisement" >Call for interview</a>

						</td>
					</tr>
				}

			</tbody>

		</table>
	}
	else
	{
		<div class="text-end my-3 p-1"> 
		   <a asp-action="ApprovedList" asp-controller="Advertisement">Applicants for interview</a> |
		   <a asp-action="List" asp-controller="Advertisement">New Applicants</a>
		</div>
		<div class="mt-3 text-center lead">It cannot be found any advertisements</div>
	}

}
</div>